on: [push, pull_request]

name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x]
    runs-on: ubuntu-latest
    services:
      localstack:
        image: localstack/localstack:latest
        ports:
          - 4566:4566
        env:
          SERVICES: s3
    env:
      AWS_SECRET_ACCESS_KEY: dummy
      AWS_ACCESS_KEY_ID: dummy
      AWS_REGION: dummy
      AWS_ENDPOINT: http://localhost:4566
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test -v -cover ./...
